SQLite:
   Filename: players


#keeprank is in seconds, 2592000 is 30 days (60*60*24*30)
votes:
   xplevels: 5
   beef: 3
   vip1: 25
   vip2: 60
   keeprank: 2592000

#List lowest to highest ranks
groups:
   vip1:
      displayname: "VIP"
      votes: 25
      ranklength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip
      loseRankCommands:
         - say %PLAYER% lost vip
      permissions:
         - some.permission.vip1
      voteAchievable: true
   vip2:
      displayname: "VIP2"
      votes: 60
      ranklength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip2
      loseRankCommands:
         - say %PLAYER% lost vip2
      permissions:
         - some.permission.vip2
      voteAchievable: true
   donor:
      displayname: "Donor"
      votes: 0
      ranklength: 2592000
      earnRankCommands:
         - say %PLAYER% given donor
         - say %PLAYER% given donor2!
      loseRankCommands:
         - say %PLAYER% lose donor :/
      permissions:
         - some.permission.donor
      voteAchievable: false
   mod:
      displayname: "Moderator"
      votes: 0
      ranklength: 0
      earnRankCommands:
         - say %PLAYER% given mod
      loseRankCommands:
         - say %PLAYER% lost mod
      permissions:
         - some.permission.mod
      voteAchievable: false
   admin:
      displayname: "Admin"
      votes: 0
      ranklength: 0
      earnRankCommands:
         - say %PLAYER% given admin
      loseRankCommands:
         - say %PLAYER% lost admin
      permissions:
         - some.permission.admin
      voteAchievable: false
   owner:
      displayname: "Owner"
      votes: 0
      ranklength: 0
      earnRankCommands:
         - say %PLAYER% given owner
      loseRankCommands:
         - say %PLAYER% lose owner
      permissions:
         - some.permission.owner
      voteAchievable: false
