SQLite:
   Filename: players

#order is important
groupperms:
   - "group.owner"
   - "group.admin"
   - "group.mod"
   - "group.vip2"
   - "group.vip"
   - "group.default"

#keeprank is in seconds, 2592000 is 30 days (60*60*24*30)
votes:
   xplevels: 5
   beef: 3
   vip1: 25
   vip2: 60
   keeprank: 2592000

#List lowest to highest vote unlockable ranks
voteranks:
   vip:
      displayname: "VIP"
      votes: 25
      ranklength: 2592000
      earncmd: ""
      losecmd: ""
   vip2:
      displayname: "VIP2"
      votes: 60
      ranklength: 2592000
      earncmd: ""
      losecmd: ""
