sqlite:
   filename: players

status_objectives:
   - "su_points"

vote_award_commands:
   - "give %PLAYER% minecraft:cooked_beef 3"
   - "xp add %PLAYER% 5 levels"

#List lowest to highest ranks
groups:
   vip1:
      displayName: "VIP"
      votesRequired: 25
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip
      loseRankCommands:
         - say %PLAYER% lost vip
      luckPermGroupName: "some.group.vip"
      voteAchievable: true
   vip2:
      displayName: "VIP2"
      votesRequired: 60
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip2
      loseRankCommands:
         - say %PLAYER% lost vip2
      luckPermGroupName: "some.group.vip2"
      voteAchievable: true
   donor:
      displayName: "Donor"
      votesRequired: 0
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% given donor
         - say %PLAYER% given donor2!
      loseRankCommands:
         - say %PLAYER% lose donor :/
      luckPermGroupName: "some.group.donor"
      voteAchievable: false
   mod:
      displayName: "Moderator"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given mod
      loseRankCommands:
         - say %PLAYER% lost mod
      luckPermGroupName: "some.group.mod"
      voteAchievable: false
   admin:
      displayName: "Admin"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given admin
      loseRankCommands:
         - say %PLAYER% lost admin
      luckPermGroupName: "some.group.admin"
      voteAchievable: false
   owner:
      displayName: "Owner"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given owner
      loseRankCommands:
         - say %PLAYER% lose owner
      luckPermGroupName: "some.group.owner"
      voteAchievable: false
