SQLite:
   Filename: players

#order is important
groupperms:
   - "group.owner"
   - "group.admin"
   - "group.mod"
   - "group.vip2"
   - "group.vip"
   - "group.default"

#keeprank is in seconds, 2592000 is 30 days (60*60*24*30)
votes:
   xplevels: 5
   beef: 3
   vip1: 25
   vip2: 60
   keeprank: 2592000

#List lowest to highest ranks
groups:
   vip1:
      displayname: "VIP"
      votes: 25
      ranklength: 2592000
      earnRankCommands:
         - lp user %PLAYER% parent removetemp vip
         - lp user %PLAYER% parent addtemp vip %EXPIRE% replace
      loseRankCommands:
         - lp user %PLAYER% parent removetemp vip
      permissions:
         - some.permission.vip1
      voteAchievable: true
   vip2:
      displayname: "VIP2"
      votes: 60
      ranklength: 2592000
      earnRankCommands:
         - lp user %PLAYER% parent removetemp vip2
         - lp user %PLAYER% parent addtemp vip2 %EXPIRE% replace
      loseRankCommands:
         - lp user %PLAYER% parent removetemp vip2
      permissions:
         - some.permission.vip2
      voteAchievable: true
   donor:
      displayname: "Donor"
      votes: 0
      ranklength: 2592000
      earnRankCommands:
         - lp user %PLAYER% parent removetemp donor
         - lp user %PLAYER% parent addtemp donor %EXPIRE% replace
      loseRankCommands:
         - lp user %PLAYER% parent removetemp donor
      permissions:
         - some.permission.donor
      voteAchievable: false
   mod:
      displayname: "Moderator"
      votes: 0
      ranklength: 0
      earnRankCommands:
         - lp user %PLAYER% parent removetemp mod
         - lp user %PLAYER% parent addtemp mod %EXPIRE% replace
      loseRankCommands:
         - lp user %PLAYER% parent removetemp mod
      permissions:
         - some.permission.mod
      voteAchievable: false
   admin:
      displayname: "Admin"
      votes: 0
      ranklength: 0
      earnRankCommands:
         - lp user %PLAYER% parent removetemp mod
         - lp user %PLAYER% parent addtemp mod %EXPIRE% replace
      loseRankCommands:
         - lp user %PLAYER% parent removetemp mod
      permissions:
         - some.permission.mod
      voteAchievable: false
   owner:
      displayname: "Owner"
      votes: 0
      ranklength: 0
      earnRankCommands: []
      loseRankCommands: []
      permissions:
         - some.permission.owner
      voteAchievable: false
