sqlite:
   filename: players


#keeprank is in seconds, 2592000 is 30 days (60*60*24*30)
votes:
   xplevels: 5
   beef: 3

#List lowest to highest ranks
groups:
   vip1:
      displayName: "VIP"
      votesRequired: 25
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip
      loseRankCommands:
         - say %PLAYER% lost vip
      permissions:
         - some.permission.vip1
      voteAchievable: true
   vip2:
      displayName: "VIP2"
      votesRequired: 60
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% earned vip2
      loseRankCommands:
         - say %PLAYER% lost vip2
      permissions:
         - some.permission.vip2
      voteAchievable: true
   donor:
      displayName: "Donor"
      votesRequired: 0
      rankLength: 2592000
      earnRankCommands:
         - say %PLAYER% given donor
         - say %PLAYER% given donor2!
      loseRankCommands:
         - say %PLAYER% lose donor :/
      permissions:
         - some.permission.donor
      voteAchievable: false
   mod:
      displayName: "Moderator"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given mod
      loseRankCommands:
         - say %PLAYER% lost mod
      permissions:
         - some.permission.mod
      voteAchievable: false
   admin:
      displayName: "Admin"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given admin
      loseRankCommands:
         - say %PLAYER% lost admin
      permissions:
         - some.permission.admin
      voteAchievable: false
   owner:
      displayName: "Owner"
      votesRequired: 0
      rankLength: 0
      earnRankCommands:
         - say %PLAYER% given owner
      loseRankCommands:
         - say %PLAYER% lose owner
      permissions:
         - some.permission.owner
      voteAchievable: false
